version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=accessform;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - uploaded_documents:/app/UploadedDocuments

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=accessform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
  
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8081:80"
    volumes:
      - uploaded_documents:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploaded_documents: 
  filebrowser_database:
  filebrowser_config: